from .effects import Borrow, borrow, borrow_mut, run, run_fn
from .memory import SharedObject, MemoryManager
from .lifetimes import Scope, Arena, Owned, Borrowed, LifetimeError, BorrowError
from .shm_arena import SharedMemoryArena, Handle
from .blob_codec import Codec, JsonCodec, MsgspecJsonCodec, alloc_object, open_object, codec_by_name
from .soa import SoASchema, SoABatchHandle, SoABatch
from .mp import OpenedView, open_handle_view, read_handle_bytes, open_handle_numpy
from .torch_stage import torch_available, tensor_tree_to_torch, pin_memory_tree, stage_tree_to_device
from .offheap import (
    OffHeapScope,
    OpenedRegion,
    borrow_region,
    borrow_region_mut,
    OffHeap,
    OffHeapBytes,
    OffHeapBlob,
    OffHeapArray,
)
from .native import (
    available as native_available,
    AtomicI64,
    RwBytes,
    NativeNotAvailable,
    shm_readinto,
    shm_write,
    handle_readinto,
    handle_write,
    ShmRingBuffer,
)
from .dataloader import (
    Producer,
    WorkerPool,
    BlobWorkerPool,
    ArrayWorkerPool,
    TensorTreeProducer,
    TensorTreeWorkerPool,
    TensorSampleProducer,
    TensorSampleWorkerPool,
    SlotArena,
    HandleMsg,
    TensorTreeDescriptor,
)
from .scopes import Frame, GlobalSegment, Published

__version__ = "0.1.0"

__all__ = [
    "Borrow",
    "borrow",
    "borrow_mut",
    "run",
    "run_fn",
    "SharedObject",
    "MemoryManager",
    "Scope",
    "Arena",
    "Owned",
    "Borrowed",
    "LifetimeError",
    "BorrowError",
    "SharedMemoryArena",
    "Handle",
    "Codec",
    "JsonCodec",
    "MsgspecJsonCodec",
    "alloc_object",
    "open_object",
    "codec_by_name",
    "SoASchema",
    "SoABatchHandle",
    "SoABatch",
    "OpenedView",
    "open_handle_view",
    "read_handle_bytes",
    "open_handle_numpy",
    "torch_available",
    "tensor_tree_to_torch",
    "pin_memory_tree",
    "stage_tree_to_device",
    "OffHeapScope",
    "OpenedRegion",
    "borrow_region",
    "borrow_region_mut",
    "OffHeap",
    "OffHeapBytes",
    "OffHeapBlob",
    "OffHeapArray",
    "native_available",
    "AtomicI64",
    "RwBytes",
    "NativeNotAvailable",
    "shm_readinto",
    "shm_write",
    "handle_readinto",
    "handle_write",
    "ShmRingBuffer",
    "Producer",
    "WorkerPool",
    "BlobWorkerPool",
    "ArrayWorkerPool",
    "TensorTreeProducer",
    "TensorTreeWorkerPool",
    "TensorSampleProducer",
    "TensorSampleWorkerPool",
    "SlotArena",
    "HandleMsg",
    "TensorTreeDescriptor",
    "Frame",
    "GlobalSegment",
    "Published",
]
